// Generated by CoffeeScript 1.9.2
var express, router;

express = require('express');

router = express.Router();

router.get('/', function(req, res, next) {
  return res.render('index', {
    title: 'Hell'
  });
});

module.exports = router;
